language: node_js
node_js:
  - 16

branches:
  only:
    - main

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Print the version for logging
  - docker --version
  # Build and tag feed-api
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed tamln2/udagram-api-feed:latest
  # Build and tag user-api
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user tamln2/udagram-api-user:latest
  # Build and tag frontend-api
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend:local tamln2/udagram-frontend:latest
  # Build and tag reverseproxy-api
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy tamln2/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tamln2/udagram-api-feed:latest
  - docker push tamln2/udagram-api-user:latest
  - docker push tamln2/udagram-frontend:latest
  - docker push tamln2/reverseproxy:latest
