version: "3" 
services:
  reverseproxy: 
    image: reverseproxy 
    ports: 
      - 8080:8080 
    restart: always 
    depends_on: 
      - backend-user 
      - backend-feed 
  backend-user: 
    image: udagram-api-user 
    environment: 
      POSTGRES_USERNAME: postgres 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: postgres 
      POSTGRES_HOST: tamln2.cl970snglyp4.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1 
      AWS_BUCKET: tamln2-udacity
      AWS_PROFILE: default
      JWT_SECRET: 12345678 
      URL: "http://localhost:8100"  
  backend-feed: 
    image: udagram-api-feed 
    volumes: 
      - /.aws:/root/.aws
    environment: 
      POSTGRES_USERNAME: postgres 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: postgres 
      POSTGRES_HOST: tamln2.cl970snglyp4.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1 
      AWS_BUCKET: tamln2-udacity
      AWS_PROFILE: default
      JWT_SECRET: 12345678 
      URL: "http://localhost:8100" 
  frontend: 
    image: udagram-frontend:v1
    ports: 
      - "8100:80"