version: 2.1

jobs:
  build-images:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker --version
            # Build and tag feed-api
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed tamln2/udagram-api-feed:latest
            # Build and tag user-api
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user tamln2/udagram-api-user:latest
            # Build and tag frontend-api
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend tamln2/udagram-frontend:v2
            # Build and tag reverseproxy-api
            docker build -t reverseproxy ./udagram-reverseproxy
            docker tag reverseproxy tamln2/reverseproxy:latest

  push-images:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: push images
          command: |
            docker --version
            docker login -u tamln2 -p Tam04031993!
            docker push tamln2/udagram-api-feed:latest
            docker push tamln2/udagram-api-user:latest
            docker push tamln2/udagram-frontend:v2
            docker push tamln2/reverseproxy:latest
workflows:
  default:
    jobs:
      - build-images
      - push-images:
          requires: [build-images]
